"""
Re-add the 360 floating ball buttons to the generated module/handler/assets.py.

module/handler/assets.py is generated by dev_tools/button_extract.py from the png files
in assets/cn/handler/, and upstream changes it whenever a button is added, so a merge of
upstream/master conflicts on it. Taking the upstream version and putting the three
expressions of this fork back is exactly what button_extract.py would produce, so the
upstream sync can resolve that conflict automatically.

Used by .github/workflows/sync-upstream.yml, run it from the repository root:

    python3 .github/scripts/resolve_generated_assets.py
"""
import re
import sys
from pathlib import Path

ASSETS_PY = Path('module/handler/assets.py')
VALID_SERVER = ['cn', 'en', 'jp', 'tw']


def expression(name, area, color):
    """
    Build the Button expression of one asset, the same way button_extract.py does.

    Args:
        name (str):
        area (tuple): Screen area of the asset, the png is a 1280x720 canvas where
            everything outside of the asset is black.
        color (tuple): Mean color of the area.

    Returns:
        str:
    """
    return '{} = Button(area={}, color={}, button={}, file={})'.format(
        name,
        {server: area for server in VALID_SERVER},
        {server: color for server in VALID_SERVER},
        {server: area for server in VALID_SERVER},
        {server: './assets/cn/handler/%s.png' % name for server in VALID_SERVER},
    )


# name: (area, color)
FLOAT_BALL_ASSETS = {
    # Right arc of the floating ball, no badge digit, see module/handler/floating_ball.py
    'FLOAT_BALL_360': ((31, 452, 44, 484), (71, 65, 63)),
    # The row "隐藏浮球" of the 360 assistant panel
    'FLOAT_BALL_360_HIDE': ((128, 530, 244, 564), (205, 205, 205)),
    # The "x" at the top right of the panel
    'FLOAT_BALL_360_CLOSE': ((759, 27, 793, 61), (228, 228, 228)),
}


def main():
    if not ASSETS_PY.exists():
        print('{} not found, run from the repository root'.format(ASSETS_PY))
        return 1

    lines = ASSETS_PY.read_text(encoding='utf-8').splitlines()

    # Everything before the first generated expression is the header, keep it verbatim
    try:
        first_expression = next(i for i, line in enumerate(lines) if re.match(r'^[A-Z0-9_]+ = ', line))
    except StopIteration:
        print('{} has no Button expression, unexpected'.format(ASSETS_PY))
        return 1

    header = lines[:first_expression]
    names = set(FLOAT_BALL_ASSETS)
    body = [line for line in lines[first_expression:]
            if line.strip() and not any(re.match(r'^{} = '.format(re.escape(name)), line) for name in names)]

    for name, (area, color) in FLOAT_BALL_ASSETS.items():
        body.append(expression(name, area, color))
    body.sort()

    with ASSETS_PY.open('w', encoding='utf-8', newline='') as f:
        for line in header + body:
            f.write(line + '\n')

    print('{}: {} buttons, {} restored'.format(ASSETS_PY, len(body), len(FLOAT_BALL_ASSETS)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
